# Generated by Django 3.0.5 on 2020-11-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201104_1347'),
        ('api', '0006_auto_20201103_1331'),
    ]

    operations = [
    ]
